name: Compile and Test Analyse Data

on:
  push:
    branches:
      - main
    paths:
      - '**.py'
      - 'Dockerfile'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set up Docker
        run: |
          sudo apt-get update && sudo apt-get install -y docker.io

      - name: Build Docker Environment
        run: |
          docker build -t reproducible-project .

      - name: Run Docker Container
        run: |
          docker run --name test-container -dit reproducible-project

      - name: Compile and Measure Results
        run: |
          docker exec test-container python3 compile_all.py compile
          docker exec test-container python3 compile_all.py measure
          docker exec test-container python3 compile_all.py clean

      - name: Analyse Data
        run: |
          docker exec test-container python3 analyse_data.py

      - name: Cleanup
        run: |
          docker stop test-container
          docker rm test-container
